group: travis_latest
language: python
cache: pip
matrix:
  include:
    - python: 3.6
      env: TORCHV=cp36
    - python: 3.7
      env: TORCHV=cp37
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
install:
  # - pip install -r requirements.txt
  - pip install flake8 yapf
  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-"${TORCHV}"-"${TORCHV}"m-linux_x86_64.whl
  - pip install torchvision
  - pip install tqdm pyyaml tensorboardX jpeg4py albumentations
  - pip install git+https://github.com/pytorch/tnt.git@master
before_script:
  # stop the build if there are any unexpected flake8 issues
  - flake8 . --count --ignore=E126,E226,E704,E731,W503,W504 --max-complexity=16 --show-source --statistics
  # exit-zero treats all errors as warnings.
  - flake8 . --count --exit-zero --max-complexity=10 --statistics
  # test to make sure the code is yapf compliant
  - ./yapf.sh --all
  - rm -rf /tmp/cifar10_data/ && PYTHONPATH=. python catalyst/dl/scripts/train.py --config=./cifar_simple/config.yml --logdir=./logs/cifar_simple
  - rm -rf /tmp/cifar10_data/ && PYTHONPATH=. python catalyst/dl/scripts/train.py --config=./cifar_stages/config.yml --logdir=./logs/cifar_stages
script:
  - true  # add other tests here
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
