model_params:
  fp16: false       # general flag
  model: simple   # model from NETWORKS to use

args:
  workers: 4
  model_dir: "cifar_simple"
  logdir: "./logs/cifar_simple"

stages:

  state_params:
    main_metric: precision01
    minimize_metric: False

  criterion_params:
      criterion: CrossEntropyLoss

  optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

  stage1:

    args:
      epochs: 10
      batch_size: 64
