model_params:
  fp16: false       # general flag
  model: simple   # model from NETWORKS to use

args:
  workers: 4
  model_dir: "cifar_stages"
  logdir: "./logs/cifar_stages"

stages:

  criterion_params:
      criterion: CrossEntropyLoss

  callbacks_params:
      precision_args: [1, 3, 5, 10]
      main_metric: precision03
      minimize_metric: false

  stage1:

    args:
      epochs: 10
      batch_size: 64

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

  # tune
  stage2:

    args:
      epochs: 5
      batch_size: 128

    optimizer_params:
      optimizer: SGD
      lr: 0.0001
      weight_decay: 0.0001

    data_params:
      reload_loaders: true