model_params:
  fp16: false       # general flag
  model: simple     # model from NETWORKS to use

args:
  workers: 4
  model_dir: "cifar_stages"
  logdir: "./logs/cifar_stages"

stages:

  state_params:
    main_metric: &reduce_metric precision01
    minimize_metric: False

  criterion_params:
      criterion: CrossEntropyLoss

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [10]
    gamma: 0.3

  callbacks_params:
    loss:
      callback: ClassificationLossCallback
    optimizer:
      callback: OptimizerCallback
    precision:
      callback: PrecisionCallback
      precision_args: [1, 3, 5]
    scheduler:
      callback: SchedulerCallback
      reduce_metric: *reduce_metric
    saver:
      callback: CheckpointCallback
    logger:
      callback: Logger
    tflogger:
      callback: TensorboardLogger

  stage1:

    args:
      epochs: 10
      batch_size: 64

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

  # tune
  stage2:

    args:
      epochs: 5
      batch_size: 128

    optimizer_params:
      optimizer: SGD
      lr: 0.0001
      weight_decay: 0.0001

    data_params:
      reload_loaders: true
